author: Laszlo Teveli
author_url: https://tevelee.github.io
readme: README.md

documentation: Documentation/*.md
abstract: Documentation/Sections/*.md

module: Eval
xcodebuild_arguments: [-scheme,Eval-Package]

output: Documentation/Output
theme: apple

github_url: https://github.com/tevelee/Eval
github_file_prefix: https://github.com/tevelee/Eval/tree/master

root_url: https://tevelee.github.io/Eval

clean: true
min_acl: internal

framework_root: Sources
source_directory: .